### ISSUE TITLE
Protoc version

### ISSUE THREAD

**Issue by ArjunBalakrishnan** [p-schulz/CarlaClientCpp#1]
Hello, 

While compiling, the version mismatch of protoc is present. 

```
#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
```

I am going to start everything from the beginning again using instructions in readme. What should I keep in mind to avoid this error? I have protoc 2.6.1 installed in my computer

**Comment by p-schulz** [comment]
Hi,

you are correct. Apperently the version of you protoc doesn't match the one used in the client. This is not intended behaviour, as protobuf libs are provided. You may need to update your installed protobuf, as two instanced of protobuffer libs are most often to cause conflicts on your system. The provided protobuffer is likely to be not present in your PATHS. 

If you don't want to change your protoc version, you could rebuild the protobuffer headers from the provided files with your installed protoc.
